### ISSUE TITLE
Tried compiling in Xcode 6.3 beta 4 and getting Initializer error

### ISSUE THREAD

**Issue by lokeuei** [unicorn/FlourishUI#1]
Getting the following errors on this line of code in modal.swift - 

 required override public init() ------> Initializer does not override a designated initializer from its superclass
  {
    super.init()  ------>  Must call a designated initializer of the superclass 'UIViewController'

**Comment by thinkclay** [comment]
Checkout latest master. I updated for Beta 4 and it's working now.
