### ISSUE TITLE
'NSInternalInconsistencyException', reason: 'Only run on the main thread!' error

### ISSUE THREAD

**Issue by ElectrumDevelopment** [unicorn/FlourishUI#10]
I have it opening the popup in a if statement and its throwing this and crashing

**Comment by thinkclay** [comment]
You can pull down the project and modify the source. All you would need to
do is change the UIVisualEffectView to a UIView and set the transparent
background accordingly.

**Comment by thinkclay** [comment]
I'm confused. Are you still trying to set the background to just a transparent color or are you using it out of the box and getting this isuse?
