### ISSUE TITLE
Completion Handler

### ISSUE THREAD

**Issue by Wilsonilo** [unicorn/FlourishUI#12]
Is there any Callback when the user closes the modal?
Thanks!

**Comment by thinkclay** [comment]
Yep https://github.com/thinkclay/FlourishUI/blob/master/Pod/Classes/Modal.swift#L124 you set the selector/action on the modal button for any callbacks you need. Line 229 is what calls the action. You could add a callback to the close() method on line 293 as well if you'd want to fork and add that in. Always open to having documentation pages or readme examples too if you'd want to contribute.

Cheers!
