### ISSUE TITLE
Cannot show FlourishUI Modal

### ISSUE THREAD

**Issue by thanhn08** [unicorn/FlourishUI#9]
Hello,

I just encountered a problem with your control, when calling show(), there is nothing happened.
After debugging, I think the problem is in this line:

Modal.swift - show() - line 250
if let rv = UIApplication.sharedApplication().keyWindow?.subviews.first

It should be subviews.last in order to make it work for me. I guess maybe because of my view architecture is a bit different, I have showing FlourishUI on a ViewController which is root controller inside a NavigationController.. this NavigationController is presented modally from 2 more ViewControllers.

Loading ViewController -- present --> Language Setting -- present -->  NavigationController (root is SignUp) ---- FlourishUI is having problem on this SignUpViewController.

I am using storyboard, running on iOS 9, XCode 7.2.1

Temporarily, I edited your code to make it work for my project, but please fix this and I will use cocoapods to update the fix.

Thank you for the nice control!

**Comment by thinkclay** [comment]
Thanks for the feedback. I think I need to conditionally check and find the active subview for this to work in multiple contexts. I'll try and update this week.
